Item/urls.py
from django.urls import *
from Item.models import Item, Photo
from Item.views import *

urlpatterns = [
    re_path(r'^$', IndexListView.as_view(), name='index'),
    re_path(r'^items/$', ItemListView.as_view(), name='items_list'),
    re_path(r'^items/(?P<pk>\d+)/$', ItemDetailView.as_view(), name='items_detail'),
    re_path(r'^photos/(?P<pk>\d+)/$', PhotoDetailView.as_view(), name='photos_detail'),
]

gallery/urls.py
from django.contrib import admin
from django.urls import *
from gallery.settings import ROOT_URL

urlpatterns = [
    re_path(r'^%s' % ROOT_URL[1:], include('gallery.real_urls')),
]

Item/models.py
from django.db import models
from django.contrib import admin
from django.urls import reverse
from Item.fields import ThumbnailImageField

''' The class Item defines a collection of Photos. Sort of like a photo album'''

class Item(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('items_detail', args=[str(self.id)])

''' Photo class defines individual photos for each item '''

class Photo(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    image = ThumbnailImageField(upload_to='photos')
    caption = models.CharField(max_length=250, blank=True)
    
    class Meta:
        ordering = ['title']

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photos_detail', args=[str(self.id)])

class PhotoInline(admin.StackedInline):
    model = Photo

class ItemAdmin(admin.ModelAdmin):
    inlines = [PhotoInline]

admin.site.register(Item, ItemAdmin)
admin.site.register(Photo)

Item/views.py
from django.shortcuts import render
from django.views.generic import list, detail
from Item.models import Item, Photo

class IndexListView(list.ListView):
    queryset = Item.objects.all()
    print(queryset)
#    print(queryset[0].get_absolute_url())
    template_name = "index.html"

class ItemListView(IndexListView):
    template_name = "items_list.html"

class ItemDetailView(detail.DetailView):
    queryset = Item.objects.all()
    template_name = "items_detail.html"

class PhotoDetailView(detail.DetailView):
    queryset = Photo.objects.all()
    template_name = "photos_detail.html"

Item/templates/base.html
<html>
        <head>
                <title>Gallery - {% block title %}{% endblock %}</title>
                <style>
                        body {  margin: 30px;
                                font-family: sans-serif;
                                background: #fff;
                        }
                        h1 { background: #ccf; padding: 20px; }
                        h2 { background: #ddf; padding: 10px 20px; }
                        h3 { background: #eef; padding: 5px 20px; }
                        table { width: 100%; }
                        table th { text-align: left; }
                </style>
        </head>
        <body>
                <h1>Gallery</h1>
                {% block content %}{% endblock %}
        </body>
</html>

Item/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<h2>Welcome to Gallery!</h2>
<p>Here you find images of various items. Use the link at the bottom to see the full listing </p>
<h3>Showcase</h3>
<table>
    <tr>
        {% for item in item_list %}
            <td>
                    <a href="{{ item.get_absolute_url }}"><b>{{ item.name }}</b><br>
                        {% if item.photo_set.count %}
                            <img src="{{ item.photo_set.all.0.image.thumb_url }}" />
                        {% else %}
                            <span>No Photos</span>
                        {% endif %}
                    </a>
            </td>
        {% endfor %}
    </tr>
</table>
<p><a href="{% url 'items_list' %}">View the full list &raquo;</a></p>
{% endblock %}

Item/templates/items_detail.html
{% extends "base.html" %}
{% block title %}{{ object.name }}{% endblock %}

{% block content %}
<p><a href="{% url 'items_list' %}">&laquo; Back to Full Listing</a></p>
<h2>{{ object.name }}</h2>
<p>{{ object.description }}</p>
<h3>Photos</h3>
<table>
    <tr>
        <th>Title</th>
        <th>Thumbnail</th>
        <th>Caption</th>
    </tr>
    {% for photo in object.photo_set.all %}
    <tr>
        <td><i>{{ photo.title }}</i></td>
        <td>
            <a href="{{ photo.get_absolute_url }}">
                <img src="{{ photo.get_image_thumb_url }}" />
            </a>
        </td>
        <td>{{ photo.caption }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

Item/templates/items_list.html
{% extends "base.html" %}
{% block title %}Item List{% endblock %}
{% block content %}
<p><a href="{% url "index" %}">&laquo; Back To Main Page</a></p>
<h2>Items</h2>
{% if object_list %}
    <table>
        <tr>
            <th>Name</th>
            <th>Sample Thumbnail</th>
            <th>Description</th>
        </tr>
        {% for item in object_list %}
        <tr>
            <td><i>{{ item.name }}</i></td>
            <td>
                {% if item.photo_set.count %}
                    <a href="{{ item.get_absolute_url }}">
                        <img src="{{ item.photo_set.all.0.image.thumb_url }}" />
                    </a>
                {% else %}
                    (No Photos Currently Uploaded)
                {% endif %}
            </td>
            <td>{{ item.description }}</td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p>There are currently no items to display</p>
{% endif %}
{% endblock %}

Item/templates/photos_detail.html
{% extends "base.html" %}
{% block title %}{{ object.name }} - {{ object.title }}{% endblock %}
{% block content %}
    <a href="{{ object.item.get_absolute_url }}">&laquo; Back to {{ object.item.name }} detail page </a>
    <h2>{{ object.item.name }} - {{ object.title }}</h2>
    <img src="{{ object.get_image_url }}" />
    {% if object.caption %}<p>{{ object.caption }}</p>{% endif %}
{% endblock %}